import { useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { nanoid } from 'nanoid'
import { createSelector } from 'reselect'
import './App.css'

type Product = { id:string; name:string; price:number; originalPrice?:number; category:string; brand:string; rating:number; reviewsCount:number; available:boolean; description:string; features:string[]; isNew?:boolean }
type Form = { name:string; price:string; originalPrice:string; category:string; brand:string; rating:number; reviewsCount:string; available:boolean; description:string; features:string[]; errors:Record<string,string> }
type State = { products:{items:Product[];categories:string[]}; form:Form; ui:{sortBy:'name'|'price'|'rating';sortOrder:'asc'|'desc';notification:string|null} }
type Action = {type:'FIELD';payload:{field:keyof Form;value:Form[keyof Form]}}|{type:'ERRORS';payload:Record<string,string>}|{type:'ADD_FEATURE';payload:string}|{type:'REMOVE_FEATURE';payload:number}|{type:'ADD_PRODUCT'}|{type:'SORT';payload:{sortBy:State['ui']['sortBy'];sortOrder:State['ui']['sortOrder']}}|{type:'CLEAR_NOTICE'}
const categories=['Смартфоны','Ноутбуки','Планшеты','Наушники','Умные часы','Фотоаппараты','Телевизоры','Игровые приставки']
const emptyForm:Form={name:'',price:'',originalPrice:'',category:categories[0],brand:'',rating:5,reviewsCount:'0',available:true,description:'',features:[],errors:{}}
export const initialState:State={products:{categories,items:[
  {id:nanoid(),name:'Nova Pro X',price:89990,originalPrice:104990,category:'Смартфоны',brand:'Nova',rating:4.9,reviewsCount:842,available:true,description:'Флагманский смартфон с профессиональной камерой',features:['256 GB','5G','OLED'],isNew:true},
  {id:nanoid(),name:'Sonic Air Studio',price:18990,category:'Наушники',brand:'Sonic',rating:4.7,reviewsCount:1284,available:true,description:'Беспроводные наушники с активным шумоподавлением',features:['ANC','40 часов','Hi-Res']},
  {id:nanoid(),name:'Orbit Book 14',price:124990,originalPrice:139990,category:'Ноутбуки',brand:'Orbit',rating:4.8,reviewsCount:326,available:false,description:'Лёгкий ноутбук для работы и творчества',features:['16 GB','1 TB SSD','2K']}
]},form:emptyForm,ui:{sortBy:'rating',sortOrder:'desc',notification:null}}
export function reducer(state=initialState,action:Action):State{switch(action.type){case'FIELD':return{...state,form:{...state.form,[action.payload.field]:action.payload.value,errors:{...state.form.errors,[action.payload.field]:''}}};case'ERRORS':return{...state,form:{...state.form,errors:action.payload}};case'ADD_FEATURE':return{...state,form:{...state.form,features:[...state.form.features,action.payload]}};case'REMOVE_FEATURE':return{...state,form:{...state.form,features:state.form.features.filter((_,i)=>i!==action.payload)}};case'ADD_PRODUCT':{const f=state.form;const product:Product={id:nanoid(),name:f.name.trim(),price:Number(f.price),originalPrice:f.originalPrice?Number(f.originalPrice):undefined,category:f.category,brand:f.brand.trim(),rating:f.rating,reviewsCount:Number(f.reviewsCount)||0,available:f.available,description:f.description.trim(),features:f.features,isNew:true};return{...state,products:{...state.products,items:[product,...state.products.items]},form:emptyForm,ui:{...state.ui,notification:'Товар успешно добавлен'}}}case'SORT':return{...state,ui:{...state.ui,...action.payload}};case'CLEAR_NOTICE':return{...state,ui:{...state.ui,notification:null}};default:return state}}
const selectSorted=createSelector([(s:State)=>s.products.items,(s:State)=>s.ui.sortBy,(s:State)=>s.ui.sortOrder],(items,by,order)=>[...items].sort((a,b)=>{const result=by==='name'?a.name.localeCompare(b.name):a[by]-b[by];return order==='desc'?-result:result}))
function validate(f:Form){const e:Record<string,string>={};if(f.name.trim().length<3)e.name='Минимум 3 символа';if(Number(f.price)<=0)e.price='Укажите цену больше 0';if(f.originalPrice&&Number(f.originalPrice)<=Number(f.price))e.originalPrice='Старая цена должна быть выше текущей';if(f.brand.trim().length<2)e.brand='Минимум 2 символа';if(f.description.trim().length<10)e.description='Минимум 10 символов';return e}
function App(){const dispatch=useDispatch();const state=useSelector((s:State)=>s);const products=useSelector(selectSorted);const [feature,setFeature]=useState('');const field=<K extends keyof Form>(key:K,value:Form[K])=>dispatch({type:'FIELD',payload:{field:key,value}});const submit=(e:React.FormEvent)=>{e.preventDefault();const errors=validate(state.form);if(Object.keys(errors).length)dispatch({type:'ERRORS',payload:errors});else{dispatch({type:'ADD_PRODUCT'});setTimeout(()=>dispatch({type:'CLEAR_NOTICE'}),2500)}}
return <main><header className="hero"><div><p>REDUX MARKET / 2026</p><h1>Вещи, которые<br/><i>работают.</i></h1></div><span>{products.length}<small>товаров в каталоге</small></span></header>{state.ui.notification&&<div className="notice">✓ {state.ui.notification}</div>}
<section className="layout"><form className="product-form" onSubmit={submit} noValidate><div className="form-head"><b>Новый товар</b><span>Все поля управляются Redux</span></div><label>Название<input aria-label="Название товара" value={state.form.name} onChange={e=>field('name',e.target.value)}/>{state.form.errors.name&&<small>{state.form.errors.name}</small>}</label><div className="two"><label>Цена<input aria-label="Цена" type="number" value={state.form.price} onChange={e=>field('price',e.target.value)}/>{state.form.errors.price&&<small>{state.form.errors.price}</small>}</label><label>Старая цена<input aria-label="Первоначальная цена" type="number" value={state.form.originalPrice} onChange={e=>field('originalPrice',e.target.value)}/>{state.form.errors.originalPrice&&<small>{state.form.errors.originalPrice}</small>}</label></div><div className="two"><label>Категория<select aria-label="Категория" value={state.form.category} onChange={e=>field('category',e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Бренд<input aria-label="Бренд" value={state.form.brand} onChange={e=>field('brand',e.target.value)}/>{state.form.errors.brand&&<small>{state.form.errors.brand}</small>}</label></div><div className="two"><label>Рейтинг: {state.form.rating}<input aria-label="Рейтинг" type="range" min="1" max="5" step="0.1" value={state.form.rating} onChange={e=>field('rating',Number(e.target.value))}/></label><label>Отзывы<input aria-label="Количество отзывов" type="number" value={state.form.reviewsCount} onChange={e=>field('reviewsCount',e.target.value)}/></label></div><label>Описание<textarea aria-label="Описание" value={state.form.description} onChange={e=>field('description',e.target.value)}/>{state.form.errors.description&&<small>{state.form.errors.description}</small>}</label><label className="check"><input aria-label="В наличии" type="checkbox" checked={state.form.available} onChange={e=>field('available',e.target.checked)}/> В наличии</label><label>Особенности<div className="feature-input"><input aria-label="Новая особенность" value={feature} onChange={e=>setFeature(e.target.value)} placeholder="Например, 5G"/><button type="button" onClick={()=>{if(feature.trim()){dispatch({type:'ADD_FEATURE',payload:feature.trim()});setFeature('')}}}>+</button></div></label><div className="tags">{state.form.features.map((x,i)=><button type="button" key={x+i} onClick={()=>dispatch({type:'REMOVE_FEATURE',payload:i})}>{x} ×</button>)}</div><button className="submit">Добавить товар</button></form>
<section className="catalog"><div className="catalog-head"><div><p>КАТАЛОГ</p><h2>Показано товаров: {products.length}</h2></div><div><select aria-label="Сортировка" value={state.ui.sortBy} onChange={e=>dispatch({type:'SORT',payload:{sortBy:e.target.value as State['ui']['sortBy'],sortOrder:state.ui.sortOrder}})}><option value="rating">По рейтингу</option><option value="price">По цене</option><option value="name">По названию</option></select><button className="order" aria-label="Порядок сортировки" onClick={()=>dispatch({type:'SORT',payload:{sortBy:state.ui.sortBy,sortOrder:state.ui.sortOrder==='asc'?'desc':'asc'}})}>{state.ui.sortOrder==='asc'?'↑':'↓'}</button></div></div><div className="grid">{products.map(p=>{const discount=p.originalPrice?Math.round((p.originalPrice-p.price)/p.originalPrice*100):0;return <article className="card" key={p.id}><div className="visual"><span>{p.category.slice(0,1)}</span><div>{p.isNew&&<b>Новинка</b>}{discount>0&&<b className="sale">−{discount}%</b>}{!p.available&&<b className="off">Нет в наличии</b>}</div></div><p className="brand">{p.brand} · {p.category}</p><h3>{p.name}</h3><p className="rating">★ {p.rating} <span>{p.reviewsCount} отзывов</span></p><div className="prices"><strong>{p.price.toLocaleString('ru-RU')} ₽</strong>{p.originalPrice&&<del>{p.originalPrice.toLocaleString('ru-RU')} ₽</del>}</div><p className="desc">{p.description}</p><div className="tags">{p.features.map(f=><span key={f}>{f}</span>)}</div></article>})}</div></section></section></main>}
export default App
